#!/bin/bash

#
# Parameters
#

LOSSLESS_DIR="/Volumes/Archive/Audio/Music"
LOSSY_DIR="~/Lossy Music"
LOG_DIR="~/Library/Logs/com.sergeyreznikov.SyncLossyLibrary"

#
# Requires MediaInfo, XLD
#

function equal_left_right {
	if [ ! -f "$1" ] || [ ! -f "$2" ]; then
		return 1
	fi
	if [ "$(stat -f %z/%m "$1")" == "$(stat -f %z/%m "$2")" ]; then
		return 0
	else
		return 1
	fi
}

function log {
	if [ -f "$1" ]; then
		echo "$2" >> "$1"
	fi
}

function realpath {
	python -c "import os, sys; print os.path.realpath(os.path.expanduser(sys.argv[1]));" "$1"
}

function requires_encoding {
	if [ "${1: -4}" == ".m4a" ] && [ $(mediainfo '--Inform=Audio;%Format%' "$1") == "ALAC" ]; then
		return 0
	else
		return 1
	fi
}

function xld {
	/Applications/XLD.app/Contents/MacOS/XLD --cmdline "$@"
}

LOSSLESS_DIR=$(realpath "$LOSSLESS_DIR")
if [ ! -d "$LOSSLESS_DIR" ]; then
	echo "No lossless directory '$LOSSLESS_DIR'"
	exit 1
fi
LOSSLESS_DIR_LENGTH=${#LOSSLESS_DIR}
LOSSY_DIR=$(realpath "$LOSSY_DIR")
if [ ! -d "$LOSSY_DIR" ]; then
	echo "No lossy directory '$LOSSY_DIR'"
	exit 1
fi
LOSSY_DIR_LENGTH=${#LOSSY_DIR}
LOG_DIR=$(realpath "$LOG_DIR")
LOG_FILE="$LOG_DIR/$(date -u +'%Y-%m-%dT%H-%M-%SZ').log"
if [ -d "$LOG_DIR" ]; then
	touch "$LOG_FILE"
fi

# Added/updated
while IFS= read -r -d '' lossless_file; do
	lossless_substring=${lossless_file:$LOSSLESS_DIR_LENGTH}
	if ! equal_left_right "$lossless_file" "$LOSSY_DIR$lossless_substring"; then
		mkdir -p "$(dirname "$LOSSY_DIR$lossless_substring")"
		if requires_encoding "$lossless_file"; then
			xld --profile Lossy -o "$LOSSY_DIR$lossless_substring" "$lossless_file"
			log "$LOG_FILE" "Encoded '$lossless_substring'"
		else
			cp "$lossless_file" "$LOSSY_DIR$lossless_substring"
			log "$LOG_FILE" "Copied '$lossless_substring'"
		fi
		if [ -f "$LOSSY_DIR$lossless_substring" ]; then
			touch -r "$lossless_file" "$LOSSY_DIR$lossless_substring"
		fi
	fi
done < <(find "$LOSSLESS_DIR" -type f \( -name '*.m4a' -or -name '*.mp3' \) -print0)

# Removed
while IFS= read -r -d '' lossy; do
	lossy_substring=${lossy:$LOSSY_DIR_LENGTH}
	if ( [ -d "$lossy" ] && [ ! -d "$LOSSLESS_DIR$lossy_substring" ] ) || ( [ -f "$lossy" ] && [ ! -f "$LOSSLESS_DIR$lossy_substring" ] ); then
		rm -drf "$lossy"
		log "$LOG_FILE" "Removed '$lossy_substring'"
	fi
done < <(find "$LOSSY_DIR" -print0)
